### ISSUE TITLE
这个报错的log文件在哪里能搞得到

### ISSUE THREAD

**Issue by woshirencai123** [logpai/loglizer#7]
Traceback (most recent call last):
  File "F:/aiops/loglizer-master/demo_bgl/classifiers_bgl.py", line 26, in <module>
    raw_data, event_mapping_data = data_loader.bgl_data_loader(para)
  File "F:\aiops\loglizer-master\demo_bgl\utils\data_loader.py", line 55, in bgl_data_loader
    data_df = pd.read_csv(file_path, delimiter=r'\s+', header=None, names = ['label','time'], usecols = para['select_column']) #, parse_dates = [1], date_parser=dateparse)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 764, in __init__
    self._make_engine(self.engine)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 985, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1605, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 394, in pandas._libs.parsers.TextReader.__cinit__ (pandas\_libs\parsers.c:4209)
  File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source (pandas\_libs\parsers.c:8873)
FileNotFoundError: File b'../../Data/BGL_data/BGL_MERGED.log' does not exist

BGL_MERGED.log不存在

**Comment by ShilinHe** [comment]
Hi there, 
As mentioned in the README, https://github.com/logpai/loghub hosts those log datasets, and the BGL data can be downloaded at https://www.usenix.org/cfdr-data.

**Comment by Satishk-Huawei** [comment]
Hi ShilinHe, From where i can download the BGL_MERGED.log and logTemplateMap.csv?
I could not get these files from https://www.usenix.org/cfdr-data

**Comment by jimzhu** [comment]
We have updated our demo code recently for readability. Pls try the new demos. @woshirencai123
