### ISSUE TITLE
issue in load_HDFS

### ISSUE THREAD

**Issue by BrilliantParth** [logpai/loglizer#80]
while executing the command: python HDFS_bechmark.py
I get this error
====== Input data summary ======
Traceback (most recent call last):
  File "HDFS_bechmark.py", line 18, in <module>
    split_type='uniform')
  File "..\loglizer\dataloader.py", line 72, in load_HDFS
    x_data = data['x_data']
  File "C:\Users\modip\anaconda3\envs\py36\lib\site-packages\numpy\lib\npyio.py", line 255, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "C:\Users\modip\anaconda3\envs\py36\lib\site-packages\numpy\lib\format.py", line 727, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

**Comment by MetaAnomie** [comment]
Changing the following line in loglizer/dataloader.py worked for me:

data = np.load(log_file) -->
data = np.load(log_file, **allow_pickle=True**)
